// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/fsufitch/bounce-paste/common"
	"github.com/fsufitch/bounce-paste/id-generator"
	"github.com/fsufitch/bounce-paste/mq"
	"os"
)

// Injectors from wire_init.go:

func InitializeServer() (*idgenerator.Server, func(), error) {
	logWriter := _wireFileValue
	logPrefix := _wireLogPrefixValue
	environ, err := common.ProvideEnvironFromProcessEnvironment()
	if err != nil {
		return nil, nil, err
	}
	debugMode := common.ProvideDebugMode(environ)
	logLevel := common.ProvideLogLevel(debugMode, environ)
	logger := common.ProvideLogger(logWriter, logPrefix, debugMode, logLevel)
	serverContext, err := ProvideServerContext(logger)
	if err != nil {
		return nil, nil, err
	}
	config, err := mq.ProvideConfigFromEnviron(logger, environ)
	if err != nil {
		return nil, nil, err
	}
	mqMQ := mq.ProvideMQ(config, logger)
	server := &idgenerator.Server{
		Context: serverContext,
		Log:     logger,
		MQ:      mqMQ,
	}
	return server, func() {
	}, nil
}

var (
	_wireFileValue      = os.Stdout
	_wireLogPrefixValue = common.LogPrefix("id-generator")
)

// wire_init.go:

func init() {
	initializerFunc = InitializeServer
}
